version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "4500:4500"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php_app1
      - php_app2
    networks:
      - app-network

  php_app1:
    build:
      context: ./php
    networks:
      - app-network
    depends_on:
      - db

  php_app2:
    build:
      context: ./php
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./db/banco.sql:/docker-entrypoint-initdb.d/banco.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
